# For Java 11,
FROM adoptopenjdk/openjdk11:alpine-jre AS APP

ARG JAR_FILE=banking-0.0.1-SNAPSHOT.jar

WORKDIR /opt/app

# Copy the banking-0.0.1-SNAPSHOT.jar from the maven stage to the /opt/app directory of the current stage.
COPY target/${JAR_FILE} /opt/app/

ENTRYPOINT ["java","-jar","banking-0.0.1-SNAPSHOT.jar"]
